//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FindDuplicates.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FindDuplicates.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Ookii_Dialogs_WinForms {
            get {
                object obj = ResourceManager.GetObject("Ookii_Dialogs_WinForms", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Buffers {
            get {
                object obj = ResourceManager.GetObject("System_Buffers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;System.Buffers&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:System.Buffers.ArrayPool`1&quot;&gt;
        ///      &lt;summary&gt;Provides a resource pool that enables reusing instances of type &lt;see cref=&quot;T[]&quot;&gt;&lt;/see&gt;.&lt;/summary&gt;
        ///      &lt;typeparam name=&quot;T&quot;&gt;The type of the objects that are in the resource pool.&lt;/typeparam&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Buffers.ArrayPool`1.#ctor&quot;&gt;
        ///      &lt;summary&gt;Initializes a new instance of the &lt;see cref=&quot;T:S [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Buffers1 {
            get {
                return ResourceManager.GetString("System_Buffers1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Memory {
            get {
                object obj = ResourceManager.GetObject("System_Memory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;System.Memory&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:System.Span`1&quot;&gt;
        ///      &lt;typeparam name=&quot;T&quot;&gt;&lt;/typeparam&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Span`1.#ctor(`0[])&quot;&gt;
        ///      &lt;param name=&quot;array&quot;&gt;&lt;/param&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Span`1.#ctor(System.Void*,System.Int32)&quot;&gt;
        ///      &lt;param name=&quot;pointer&quot;&gt;&lt;/param&gt;
        ///      &lt;param name=&quot;length&quot;&gt;&lt;/param&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Span`1.#ctor(` [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Memory1 {
            get {
                return ResourceManager.GetString("System_Memory1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Numerics_Vectors {
            get {
                object obj = ResourceManager.GetObject("System_Numerics_Vectors", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;System.Numerics.Vectors&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:System.Numerics.Matrix3x2&quot;&gt;
        ///      &lt;summary&gt;Represents a 3x2 matrix.&lt;/summary&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Numerics.Matrix3x2.#ctor(System.Single,System.Single,System.Single,System.Single,System.Single,System.Single)&quot;&gt;
        ///      &lt;summary&gt;Creates a 3x2 matrix from the specified components.&lt;/summary&gt;
        ///      &lt;param name=&quot;m11&quot;&gt;The value to assign to the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Numerics_Vectors1 {
            get {
                return ResourceManager.GetString("System_Numerics_Vectors1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Resources_Extensions {
            get {
                object obj = ResourceManager.GetObject("System_Resources_Extensions", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;doc&gt;
        ///    &lt;assembly&gt;
        ///        &lt;name&gt;System.Resources.Extensions&lt;/name&gt;
        ///    &lt;/assembly&gt;
        ///    &lt;members&gt;
        ///        &lt;member name=&quot;M:System.Resources.Extensions.PreserializedResourceWriter.AddResource(System.String,System.String,System.String)&quot;&gt;
        ///            &lt;summary&gt;
        ///            Adds a resource of specified type represented by a string value.
        ///            If the type is a primitive type, the value will be converted using TypeConverter by the writer
        ///            to that primitive type an [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Resources_Extensions1 {
            get {
                return ResourceManager.GetString("System_Resources_Extensions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] System_Runtime_CompilerServices_Unsafe {
            get {
                object obj = ResourceManager.GetObject("System_Runtime_CompilerServices_Unsafe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;&lt;doc&gt;
        ///  &lt;assembly&gt;
        ///    &lt;name&gt;System.Runtime.CompilerServices.Unsafe&lt;/name&gt;
        ///  &lt;/assembly&gt;
        ///  &lt;members&gt;
        ///    &lt;member name=&quot;T:System.Runtime.CompilerServices.Unsafe&quot;&gt;
        ///      &lt;summary&gt;Contains generic, low-level functionality for manipulating pointers.&lt;/summary&gt;
        ///    &lt;/member&gt;
        ///    &lt;member name=&quot;M:System.Runtime.CompilerServices.Unsafe.Add``1(``0@,System.Int32)&quot;&gt;
        ///      &lt;summary&gt;Adds an element offset to the given reference.&lt;/summary&gt;
        ///      &lt;param name=&quot;source&quot;&gt;The refe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string System_Runtime_CompilerServices_Unsafe1 {
            get {
                return ResourceManager.GetString("System_Runtime_CompilerServices_Unsafe1", resourceCulture);
            }
        }
    }
}
